version: '2'

services:
  mysql_server:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: yoursecret
    ports:
      - 3306:3306
    restart: always
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf
  redis_server:
    image: redis:3.2.11
    command: ["redis-server"]
    restart: always
    ports:
      - 6379:6379
  mongodb_server:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    command: ["mongod", "--master", "--smallfiles", "--logpath=/dev/null"]
  rabbitmq_server:
    image: rabbitmq:3.7.4-management
    hostname: "rabbitmq.local"
    environment:
      RABBITMQ_ERLANG_COOKIE: "X0DYOLVQWLISXX9G"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
  postgres_server:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "yoursecret"
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    hostname: "adminer.local"
    ports:
      - 8090:8080
  swagger_editor:
    image: swaggerapi/swagger-editor
    hostname: "swagger-editor.local"
    ports:
      - 8091:8080

networks: 
  default:
    external:
      name: my-shared-network
